package com.researchworx.cresco.controller.graphdb;

import com.researchworx.cresco.controller.communication.ActiveBrokerManager;
import com.researchworx.cresco.controller.core.Launcher;
import com.researchworx.cresco.controller.regionalcontroller.AgentNode;
import com.researchworx.cresco.library.messaging.MsgEvent;
import com.researchworx.cresco.library.utilities.CLogger;

import java.util.Map;
import java.util.Timer;
import java.util.TimerTask;

public class GraphDBUpdater {

    private Map<String, AgentNode> agentMap;
    private Launcher plugin;
    private CLogger logger;
    private GraphDBEngine rgdb;
    private Timer regionalUpdateTimer;


    public GraphDBUpdater(Launcher plugin) {
        this.logger = new CLogger(GraphDBUpdater.class, plugin.getMsgOutQueue(), plugin.getRegion(), plugin.getAgent(), plugin.getPluginID(), CLogger.Level.Info);

        this.plugin = plugin;
        rgdb = new GraphDBEngine(plugin,true);
        regionalUpdateTimer = new Timer();
        regionalUpdateTimer.scheduleAtFixedRate(new GraphDBUpdater.RegionalWatchDog(logger), 500, 15000);//remote
    }

    /*
    public Boolean isNode(String region, String agent, String plugin) {
        boolean isNode = false;
        try {
            String nodeId = rgdb.getNodeId(region,agent,plugin);
            if(nodeId != null) {
                logger.trace("region: " + region + " agent:" + agent + " plugin:" + plugin + " id:" + nodeId);
                logger.trace("params: " + rgdb.getNodeParams(nodeId).toString());
                if(plugin != null) {
                    String nodeAgentId = rgdb.getNodeId(region,agent,null);
                    logger.trace("region: " + region + " agent:" + agent + " plugin:" + " null id:" + nodeAgentId);
                    logger.trace("params: " + rgdb.getNodeParams(nodeAgentId).toString());
                }
                isNode = true;
            }

        } catch (Exception ex) {
            logger.error("GraphDBUpdater : isNode ERROR : " + ex.toString());
        }
        return isNode;
    }
    */
    public MsgEvent controllerMsgEvent(String region, String agent, String plugin, String controllercmd) {
        MsgEvent ce = new MsgEvent(MsgEvent.Type.CONFIG, null, null, null, "Generated by ControllerDB");
        ce.setParam("controllercmd", controllercmd);
        if ((region != null) && (agent != null) && (plugin != null)) {
            ce.setParam("src_region", region);
            ce.setParam("src_agent", agent);
            ce.setParam("src_plugin", plugin);

        } else if ((region != null) && (agent != null)) {
            ce.setParam("src_region", region);
            ce.setParam("src_agent", agent);
        }
        return ce;
    }

    public Boolean addNode(MsgEvent de) {
        Boolean wasAdded = false;

        try {

            String region = de.getParam("src_region");
            String agent = de.getParam("src_agent");
            String plugin = de.getParam("src_plugin");

            String nodeId = rgdb.getNodeId(region,agent,plugin);
            if(nodeId != null) {
                logger.trace("region: " + region + " agent:" + agent + " plugin:" + plugin + " id:" + nodeId);
                logger.trace("params: " + rgdb.getNodeParams(nodeId).toString());
                if(plugin != null) {
                    String nodeAgentId = rgdb.getNodeId(region,agent,null);
                    logger.trace("region: " + region + " agent:" + agent + " plugin:" + " null id:" + nodeAgentId);
                    logger.trace("params: " + rgdb.getNodeParams(nodeAgentId).toString());
                }
            }
            else {
                logger.debug("Adding Node: " + de.getParams().toString());
                rgdb.addNode(region, agent,plugin);
                rgdb.setNodeParams(region,agent,plugin, de.getParams());
                rgdb.setNodeParam(region,agent,plugin, "watchdog_ts", String.valueOf(System.currentTimeMillis()));
                wasAdded = true;
            }

        } catch (Exception ex) {
            logger.error("GraphDBUpdater : addNode ERROR : " + ex.toString());
        }
        return wasAdded;
    }

    public Boolean watchDogUpdate(MsgEvent de) {
        Boolean wasUpdated = false;

        try {

            String region = de.getParam("src_region");
            String agent = de.getParam("src_agent");
            String plugin = de.getParam("src_plugin");

            String nodeId = rgdb.getNodeId(region,agent,plugin);
            if(nodeId != null) {
                logger.debug("Updating WatchDog Node: " + de.getParams().toString());
                rgdb.setNodeParam(region,agent,plugin, "watchdog_ts", String.valueOf(System.currentTimeMillis()));
                wasUpdated = true;
            }
            else {
                logger.error("watchDogUpdate : Can't update missing node : " + de.getParams().toString());
            }

        } catch (Exception ex) {
            logger.error("GraphDBUpdater : watchDogUpdate ERROR : " + ex.toString());
        }
        return wasUpdated;
    }

    /*
    public void addNode(String region, String agent, String plugin, Map<String,String> params) {
        logger.info("Adding Node: " + region + " " + agent + " " + plugin);
        try {
            rgdb.addNode(region, agent,plugin);
            rgdb.setNodeParams(region,agent,plugin, params);
        } catch (Exception ex) {
            logger.error("GraphDBUpdater : addNode ERROR : " + ex.toString());
        }
    }
    */

    public void setNodeParams(String region, String agent, String plugin, Map<String, String> paramMap) {
        //extract config from param Map
        Map<String, String> configMap = this.plugin.getControllerConfig().buildPluginMap(paramMap.get("msg"));

        try {

            if ((region != null) && (agent != null) && (plugin == null)) //agent node
            {
                agentMap.get(agent).setAgentParams(configMap);
                if (this.plugin.hasGlobalController()) {
                    MsgEvent ce = controllerMsgEvent(region, agent, plugin, "setparams");
                    ce.setParam("configparams", paramMap.get("msg"));
                    if (!this.plugin.getGlobalControllerChannel().setNodeParams(ce)) {
                        System.out.println("Controller : ControllerDB : Failed to setParams for Node on Controller");
                    }
                }
            } else if ((region != null) && (agent != null) && (plugin != null)) //plugin node
            {
                agentMap.get(agent).setPluginParams(plugin, configMap);
                if (this.plugin.hasGlobalController()) {
                    MsgEvent ce = controllerMsgEvent(region, agent, plugin, "setparams");
                    ce.setParam("configparams", paramMap.get("msg"));
                    if (!this.plugin.getGlobalControllerChannel().setNodeParams(ce)) {
                        System.out.println("Controller : ControllerDB : Failed to setParams for Node on Controller");
                    }
                }
            }
        } catch (Exception ex) {
            System.out.println("Controller : ControllerDB : setNodeParams ERROR : " + ex.toString());
        }
    }

    public Map<String, String> getNodeParams(String region, String agent, String plugin) {
        try {
            if ((region != null) && (agent != null) && (plugin == null)) //agent node
            {
                return agentMap.get(agent).getAgentParams();
            } else if ((region != null) && (agent != null) && (plugin != null)) //plugin node
            {
                return agentMap.get(agent).getPluginParams(plugin);
            }
            return null;
        } catch (Exception ex) {
            System.out.println("Controller : ControllerDB : getNodeParams ERROR : " + ex.toString());
            return null;
        }
    }


    public void setNodeParam(String region, String agent, String plugin, String key, String value) {
        try {
            if ((region != null) && (agent != null) && (plugin == null)) //agent node
            {
                agentMap.get(agent).setAgentParam(key, value);
            } else if ((region != null) && (agent != null) && (plugin != null)) //plugin node
            {
                agentMap.get(agent).setPluginParam(plugin, key, value);
            }
        } catch (Exception ex) {
            System.out.println("Controller : ControllerDB : setNodeParam ERROR : " + ex.toString());
        }
    }

    public Boolean removeNode(MsgEvent de) {
        Boolean wasRemoved = false;

        try {

            String region = de.getParam("src_region");
            String agent = de.getParam("src_agent");
            String plugin = de.getParam("src_plugin");

            String nodeId = rgdb.getNodeId(region,agent,plugin);
            if(nodeId != null) {
                logger.debug("Removing Node: " + de.getParams().toString());
                rgdb.removeNode(region, agent,plugin);
                wasRemoved = true;
            }
            else {
                logger.error("region: " + region + " agent:" + agent + " plugin:" + plugin + " does not exist!");
            }

        } catch (Exception ex) {
            logger.error("GraphDBUpdater : removeNode ERROR : " + ex.toString());
        }
        return wasRemoved;
    }

    public Boolean removeNode(String region, String agent, String plugin) {
        Boolean wasRemoved = false;

        try {

            String nodeId = rgdb.getNodeId(region,agent,plugin);
            if(nodeId != null) {
                logger.debug("Removing Node: " + "region: " + region + " agent:" + agent + " plugin:" + plugin);
                rgdb.removeNode(region, agent,plugin);
                wasRemoved = true;
            }
            else {
                logger.error("region: " + region + " agent:" + agent + " plugin:" + plugin + " does not exist!");
            }

        } catch (Exception ex) {
            logger.error("GraphDBUpdater : removeNode ERROR : " + ex.toString());
        }
        return wasRemoved;
    }

    class RegionalWatchDog extends TimerTask {
        private CLogger logger;

        public RegionalWatchDog(CLogger logger) {
            this.logger = logger;
        }
        public void run() {
            for(String node_id : rgdb.getNodeIds("region",null,null)) {
                Map<String,String> nodeParams = rgdb.getNodeParams(node_id);

                long watchdog_ts = Long.parseLong(nodeParams.get("watchdog_ts"));
                long watchdog_rate = Long.parseLong(nodeParams.get("watchdog_rate"));
                long watchdog_diff = System.currentTimeMillis() - watchdog_ts;

                logger.info("node_id: " + node_id + " [" + rgdb.getNodeParams(node_id).toString() + "]");
                logger.info("WatchDog Diff = " + String.valueOf(watchdog_diff) + " watchdog_rate: " + watchdog_rate);

            }

        }
    }


}
